CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  desc TEXT,
  date TEXT NOT NULL,
  category TEXT NOT NULL,
  image TEXT,
  featured INTEGER DEFAULT 0
);
