CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  desc TEXT,
  date TEXT NOT NULL,
  category TEXT NOT NULL,
  image TEXT,
  featured INTEGER DEFAULT 0
);

CREATE TABLE players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  number INTEGER NOT NULL,
  position TEXT NOT NULL,
  role TEXT NOT NULL,
  foot TEXT NOT NULL,
  image TEXT NOT NULL
);
